### ISSUE TITLE
请教一下：当合约部署到了appchain测试网络后，有地方可以查询到该合约的数据状态情况嘛？

### ISSUE THREAD

**Issue by JackyKen** [cryptape/dapp-demos#24]
我在本地部署了一个first_forever中的SimpleStore的合约到appchain的测试网络，合约地址：0xb7Be95737BeF4913C27Fe60fd8FcdC97a6ceFD8B，在本地启动前端应用启动后，操作dapp发现可以添加留言，按钮会从保存中->保存成功，但是在不能查询到所有留言记录。是因为交易可能还没被确认吗？还是我不能再本地进行交易，必须要在在neuron 钱包中打开dapp应用？

**Comment by Keith-CY** [comment]
如果你用 master 分支, 则必须在 neuron 中打开应用
如果你用 develop 分支, 则支持在 web 上直接使用
